### ISSUE TITLE
Build LVR on Mac OSX

### ISSUE THREAD

**Issue by apatzer** [lasvegasrc/Las-Vegas-Reconstruction#19]
If you try to build LVR on Mac OSX (I used Mavericks), you may run into a conflict with VTK6 and PCL (Point Cloud Library).  Take a look at the discussion at http://stackoverflow.com/questions/35328483/ld-library-not-found-for-lvtkftgl if you get a `ld: library not found for -lvtkftgl`

You also need to install QT with support for QT3 deprecated packages, or the LVR UI system will not work on OSX.

```
brew install qt --with-qt3support
```

After installing all the required external packages, you will then eventually get to a `missing <omp.h>` as CLang does not have OMP multi-threading and SIMD instructions built-in by default.

You should do:

```
brew install clang-omp
```

And in your CMakeLists.txt towards the top add:

```
if(APPLE)
  set(CMAKE_C_COMPILER /usr/local/bin/clang-omp CACHE STRING "C compiler" FORCE)
  set(CMAKE_CXX_COMPILER /usr/local/bin/clang-omp++ CACHE STRING "C++ compiler" FORCE)
endif(APPLE)
```

Then run

```
CC=clang-omp CXX=clang-omp++ cmake -DCMAKE_BUILD_TYPE=Release ..
```

inside your build directory followed by `make`

At this point (hopefully) everything will work.

**Comment by lasvegasrc** [comment]
Thanks for the hints. VTK6 is also causing trouble if you try to compile the CUDA stuff, so I currently only use VTK5. Concerning the missing OpenMP support (which actually is a shame): The software should compile without a OpenMP supporting. I'm not a fan of hardcoding the compiler calls, but I will add your suggestion as an convenience build option.

**Comment by lasvegasrc** [comment]
I integrated your patch in master and cmake now uses clang-omp to compile but no performace improvement :-(

**Comment by lasvegasrc** [comment]
This software is no longer supported. We have a total rewrite (LVR2) available in this repository: https://github.com/uos/lvr2. Please use the new version. Thx.
