### ISSUE TITLE
Unable to parse options. Call 'reconstruct --help' for more information.

### ISSUE THREAD

**Issue by wsAndy** [lasvegasrc/Las-Vegas-Reconstruction#20]
In   '/src/tools/reconstruct/Options.cpp' .
In line 227,  ' return m_variables.count("textureAnalyis"); ' , this line lose a 's' in 'textureAnalyis'.

**Comment by lasvegasrc** [comment]
This software is no longer supported. We have a total rewrite (LVR2) available in this repository: https://github.com/uos/lvr2. Please use the new version. Thx.
