### ISSUE TITLE
how to generate texture from colored point clouds?

### ISSUE THREAD

**Issue by wsAndy** [lasvegasrc/Las-Vegas-Reconstruction#21]
In the [websit](http://www.las-vegas.uni-osnabrueck.de/) ,it is said that we could generate textures from colored point clouds or laser scanner intensity values.
But I can not make it. What I get is that all the pointclouds become green with the below information
-----------Texturizer statistiscs-----------
Texturized Planes: 27
Matched individual textures: 0
Matched pattern textures: 0
Extracted Patterns: 0

When I input>  
./lvr_reconstruct --inputFile ./cloud.ply -v 0.05 --generateTextures --textureAnalysis -o --classifier PlaneSimpsons -t --texelSize 0.01 -r --nsc 16 --nccv 64 --intersections -1 -c -s --cro --ransac

**Comment by twiemann** [comment]
Hi, 

I just pushed a fix for this issue into the master branch. The search trees were broken and did not return color information.

-- Thomas
