### ISSUE TITLE
build LVR failed in ubuntu 14.04

### ISSUE THREAD

**Issue by linzha0** [lasvegasrc/Las-Vegas-Reconstruction#34]
When I built LVR, got issure shown below:  

     /usr/include/vtk-5.8/QVTKWidget.h:40:25: fatal error: QtGui/QWidget: No such file or directory
      #include <QtGui/QWidget>

**System:**

Qt version:
> QMake version 3.1
> Using Qt version 5.9.2 in /opt/Qt5.9.2/5.9.2/gcc_64/lib

PCL: > 1.8 ,master version right now from github

I think it's vtk vs qt problem. coule you tell me what's the version you used. any suggestions? thank you.

**Comment by lasvegasrc** [comment]
This software is no longer supported. We have a total rewrite (LVR2) available in this repository: https://github.com/uos/lvr2. Please use the new version. Thx.
